=== brat002/ExpertBilling/mdi/reports/xml/report_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="report">
    <xs:complexType>
      <xs:sequence>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="textformat">
            <xs:complexType>
              <xs:complexContent mixed="false">
                <xs:extension base="textformat" />
              </xs:complexContent>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="blockformat" type="blockformat" />
        </xs:sequence>
        <xs:element name="frame">
          <xs:complexType>
            <xs:complexContent mixed="false">
              <xs:extension base="frame">
                <xs:choice />
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="frame">
    <xs:all minOccurs="0" maxOccurs="1">
      <xs:element minOccurs="0" maxOccurs="1" name="frame" type="frame" />
      <xs:element minOccurs="0" name="inserttext" type="insertText" />
      <xs:element minOccurs="0" name="insertblock" type="insertBlock" />
      <xs:element minOccurs="0" name="frameformat" type="frameformat" />
      <xs:element minOccurs="0" name="chart" type="chart" />
      <xs:element minOccurs="0" name="table">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension base="table" />
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="insertnontext" type="insertNonText" />
      <xs:element minOccurs="0" name="insertdatatext" type="insertDataText" />
      <xs:element minOccurs="0" name="insertdatanontext" type="insertDataNonText" />
      <xs:element minOccurs="0" name="data">
        <xs:complexType>
          <xs:attribute name="dataid" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="format" type="xs:string" use="optional" />
    <xs:attribute name="fname" type="xs:string" use="optional" />
    <xs:attribute name="formattype" use="optional" />
    <xs:attribute name="setBorder" use="optional" />
    <xs:attribute name="setHeight" use="optional" />
    <xs:attribute name="setWidth" use="optional" />
    <xs:attribute name="setPosition" use="optional" />
    <xs:attribute name="setMargin" use="optional" />
    <xs:attribute name="setPadding" use="optional" />
    <xs:attribute name="setBorderStyle" use="optional" />
    <xs:attribute name="datasource" use="optional" />
    <xs:attribute name="setBackground" use="optional" />
    <xs:attribute name="setTextColor" />
  </xs:complexType>
  <xs:complexType name="insertText">
    <xs:attribute name="text" type="xs:string" />
    <xs:attribute name="textformat" use="optional" />
  </xs:complexType>
  <xs:complexType name="insertBlock">
    <xs:attribute name="number" use="optional" />
    <xs:attribute name="blockformat" use="optional" />
  </xs:complexType>
  <xs:complexType name="chart">
    <xs:all minOccurs="0" maxOccurs="1">
      <xs:element minOccurs="0" name="charttable" type="table" />
      <xs:element minOccurs="0" maxOccurs="1" name="frameformat">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension base="frameformat" />
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="getdata">
        <xs:complexType>
          <xs:all maxOccurs="1">
            <xs:element minOccurs="0" name="selstring">
              <xs:complexType>
                <xs:attribute name="name" use="required" />
                <xs:attribute name="type" use="required" />
                <xs:attribute name="dataid" />
              </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="frame" type="frame" />
            <xs:element minOccurs="0" name="table" type="table" />
          </xs:all>
          <xs:attribute name="name" use="optional" />
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="options" />
      <xs:element minOccurs="0" name="frame" type="frame" />
    </xs:all>
    <xs:attribute name="library" use="optional" />
    <xs:attribute name="name" />
    <xs:attribute name="type" />
    <xs:attribute name="outtype" use="optional" />
  </xs:complexType>
  <xs:complexType name="frameformat">
    <xs:attribute name="setBorder" use="optional" />
    <xs:attribute name="setHeight" use="optional" />
    <xs:attribute name="setWidth" use="optional" />
    <xs:attribute name="setPosition" use="optional" />
    <xs:attribute name="setMargin" use="optional" />
    <xs:attribute name="setBorderStyle" use="optional" />
    <xs:attribute name="setPadding" use="optional" />
    <xs:attribute name="format" use="optional" />
    <xs:attribute name="fname" use="optional" />
    <xs:attribute name="name" use="optional" />
    <xs:attribute name="setBorder" use="optional" />
  </xs:complexType>
  <xs:complexType name="textformat">
    <xs:attribute name="name" />
    <xs:attribute name="setFontWeight" use="optional" />
    <xs:attribute name="setFontItalic" use="optional" />
    <xs:attribute name="setFontUnderline" use="optional" />
    <xs:attribute name="setFontFamily" use="optional" />
    <xs:attribute name="setFontPointSize" use="optional" />
    <xs:attribute name="setForeground" use="optional" />
    <xs:attribute name="setBackground" use="optional" />
  </xs:complexType>
  <xs:complexType name="table">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="column">
        <xs:complexType>
          <xs:attribute name="name" use="optional" />
          <xs:attribute name="type" />
          <xs:attribute name="format" use="optional" />
          <xs:attribute name="nameformat" use="optional" />
          <xs:attribute name="datasource" use="optional" />
          <xs:attribute name="imerge" use="optional" />
          <xs:attribute name="ibase" use="optional" />
          <xs:attribute name="tftype" use="optional" />
          <xs:attribute name="tformat" use="optional" />
          <xs:attribute name="tfname" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" />
    <xs:attribute name="columns" />
    <xs:attribute name="fname" use="required" />
    <xs:attribute name="ftype" />
    <xs:attribute name="setAlignment" use="optional" />
    <xs:attribute name="setCellPadding" use="optional" />
    <xs:attribute name="setCellSpacing" use="optional" />
    <xs:attribute name="data" use="optional" />
    <xs:attribute name="dictdata" use="optional" />
    <xs:attribute name="datasource" use="optional" />
    <xs:attribute name="type" use="required" />
    <xs:attribute name="arheader" use="optional" />
    <xs:attribute name="colnametf" />
    <xs:attribute name="arheadtf" />
    <xs:attribute name="celltf" />
    <xs:attribute name="arheadbf" use="optional" />
    <xs:attribute name="colConstrType" use="optional" />
    <xs:attribute name="colConstraints" use="optional" />
  </xs:complexType>
  <xs:complexType name="insertNonText">
    <xs:complexContent mixed="false">
      <xs:extension base="insertText">
        <xs:attribute name="format" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="insertDataText">
    <xs:complexContent mixed="false">
      <xs:extension base="insertText">
        <xs:attribute name="dict" use="optional" />
        <xs:attribute name="key" use="optional" />
        <xs:attribute name="index" use="optional" />
        <xs:attribute name="subindex" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="insertDataNonText">
    <xs:complexContent mixed="false">
      <xs:extension base="insertDataText">
        <xs:attribute name="format" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="moveCursor">
    <xs:attribute name="position" />
    <xs:attribute name="type" />
    <xs:attribute name="framename" use="optional" />
  </xs:complexType>
  <xs:complexType name="blockformat">
    <xs:attribute name="setAlignment" />
    <xs:attribute name="name" />
  </xs:complexType>
</xs:schema>

=== brat002/ExpertBilling/mdi/reports/xml/report3_tr.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="18" setFontItalic="true" setForeground="#00ff00"/>
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" />
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
	<insertblock blockformat="bf1"/>
	<chart library="pychartdir" name="chart1" type="trans_deb">
	</chart>
	<frame name="fr2" datasource="args" type="current" format="currentnew" fname="tff1">
		<insertblock />
		<insertblock />
		<inserttext text="Дата начала: " textformat="tf2" />
		<insertdatanontext index = '0' />
		<insertblock />
		<inserttext text="Дата окончания: "/>
		<insertdatanontext index = '1' />
		<insertblock />
		<insertblock />
	</frame>
  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3_multcl.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
	<textformat name="whitetf10" setFontWeight="72" setFontPointSize="10" setForeground="#FFFFFF" />
	<textformat name="stf1" setFontWeight="72" setFontPointSize="12" setForeground="#3d3d3d" />
	<textformat name="stf2" setFontWeight="72" setFontPointSize="11" setForeground="#5e93b6" />
	<textformat name="stf3" setFontWeight="36" setFontPointSize="11" setForeground="#000000" />
	<blockformat name="centerbf" setAlignment="22" />
	<frame name="topframe" format="currentedit" setWidth="840" fname="topff" padding="0">
		<image path="images/reports/header.png" />
		<frame name="uprblockfr" format="new" fname="ubff" setHeight="50" setWidth="840" padding="4" setBackground="#323232">
			<insertblock blockformat="centerbf" />
			<inserttext text="Скорость по портам" textformat="whitetf10" />
			<insertblock />
		</frame>
		<frame name="cframe" type="existing" format="new" setWidth="840" fname="cff">
			<insertblock blockformat="centerbf" />
			<chart library="pychartdir" name="chart1" type="nfs_multi_classes_speed">
				<getdata>
				</getdata>
			</chart>
		</frame>
		<frame name="chtbl2fr" datasource="args" type="current" format="currentnew" setWidth="840" fname="chtbl2ff">
			<insertblock />
			<insertblock blockformat="centerbf" />
			<inserttext text="ПЕРИОД: " textformat="stf1" />
			<inserttext text="с " textformat="stf3" />
			<insertdatanontext index="0" textformat="stf2" />
			<inserttext text=" по " textformat="stf3" />
			<insertdatanontext index="1" textformat="stf2" />
			<insertblock />
			<insertblock />
		</frame>
	</frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3_nas_nas.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="14" />
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" />
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
	  <insertblock blockformat="bf1"/>
      <inserttext text="Отчёт по классам траффика с выбором сервера доступа" textformat="tf1"/>
      <insertblock blockformat="defbf"/>
    </frame>    
    <insertblock />
	<insertblock />
	<insertblock />

	<chart library="pychartdir" name="chart1" type="nfs_nas_traf">
		<frame name="fr2" datasource="args" type="current" format="currentnew" fname="tff1">
			<insertblock />
			<inserttext text="Дата начала: " textformat="tf2" />
			<insertdatanontext index = '0' />
			<insertblock />
			<inserttext text="Дата окончания: "/>
			<insertdatanontext index = '1' />
			<insertblock />
		</frame>
		<getdata>
			<selstring name="get_nas" dataid="ch1datanas"/>
			<insertblock/>			
			<frame name="ch1fr4" datasource="ch1datanas" type="current" format="current">
				<table name="tbl3" columns="2" type="normal" ftype="new" setCellPadding="2"  setBackground="#c0a0c0" fname="tf2" arheader="Выбранный сервер доступа: ">
					<column name="Имя" type="string" />
					<column name="Тип" type="string" />
				</table>
			</frame>
		</getdata>		
	</chart>

  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="77" setFontItalic="true" setForeground="#00ff00"/>
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
      <inserttext text="string" />
      <insertblock />
    </frame>
    <inserttext text="дапашолты" />
    <insertblock />
	<chart library="pychartdir" name="chart1" type="nfs_user_traf">
		<getdata>
			<selstring name="get_accounts" dataid="ch1data1"/>
			<frame name="ch1fr1" datasource="ch1data1" type="current" format="current">
				<inserttext text="ID"/>
				<insertblock/>
				<insertdatanontext index = '0' subindex="0"/>
				<insertblock/>
				<inserttext text="uname"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="1"/>
				<insertblock blockformat="bf1"/>
				<inserttext text="VPN IP"/>
				<insertblock blockformat="defbf"/>
				<insertdatatext index = '0' subindex="2"/>
				<insertblock/>
				<inserttext text="UPN IP"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="3"/>
				<insertblock/>
				<inserttext text="                  "/>
				<table name="tbl2" columns="4" type="normal"  fname="tf2" ftype="new" setCellPadding="2" celltf="tf1" setBackground="#c0a0c0" >
					<column name="ID" type="int" />
					<column name="uname" type="string" />
					<column name="vpn ip" type="string" />
					<column name="upn ip" type="string" />
				</table>
			</frame>			
		</getdata>
		<getdata>
			<selstring name="get_tarifs" dataid="ch1data2"/>
			<frame name="ch1fr2" datasource="ch1data2"  format="new" fname="nnn" setBorder="12" setBorderStyle="2" setPosition="0" setWidth="69%" setBackground="#c0a0c0" >
				<inserttext text="ZOMG TABLE" textformat="tf1"/>
				<insertblock/>
				<table name="tbl1" columns="2" type="array" arheader="              Table for account ID: %d" setAlignment="22" fname="tf1" ftype="new" colnametf="tf1" arheadtf="tf1" arheadbf="bf1">
					<column name="Tariff" type="string" />
					<column name="Date" type="string" />
				</table>
			</frame>
		</getdata>
	</chart>
	<inserttext text="ахшобцибя"/>
	<insertblock/>
  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report_table.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat setFontWeight="string" setFontUnderline="string" setFontFamily="string" />
  <frame name="string" type="string" setHeight="string" setPosition="string" setMargin="string">
    <frame name="string" type="string" format="string" fname="string" formattype="string">
      <frame format="string" fname="string" formattype="string" setBorder="string" setWidth="string" setPosition="string" setMargin="string" setBorderStyle="string">
        <frame name="string" type="string" format="string" fname="string" formattype="string" setHeight="string" setWidth="string" setPosition="string" setMargin="string" />
      </frame>
      <inserttext text="string" />
      <insertblock />
    </frame>
    <inserttext textformat="string" />
    <insertblock number="string" />
  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3_sess.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="18" setFontItalic="true" setForeground="#00ff00"/>
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" setForeground="#00ff00"/>
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
	  <insertblock blockformat="bf1"/>
      <inserttext text="Сессии" textformat="tf1"/>
      <insertblock blockformat="defbf"/>
    </frame>    
    <insertblock />
	<insertblock />
	<insertblock />
	<frame name="fr2" datasource="args" type="current" format="currentnew" fname="tff1">
		<insertblock />
		<insertblock />
		<inserttext text="Дата начала: " textformat="tf2" />
		<insertdatanontext index = '1' />
		<insertblock />
		<inserttext text="Дата окончания: "/>
		<insertdatanontext index = '2' />
		<insertblock />
		<insertblock />
	</frame>
	<chart library="pychartdir" name="chart1" type="sessions">
		<getdata>
			<frame name="ch1fr1" datasource="chart1_return" type="current" format="current">
				<inserttext text="Таблица "/>
				<insertblock/>
				<inserttext text="               "/>
				<table name="tbl2" columns="5" type="normal"  fname="tf2" ftype="new" setCellPadding="2"  setBackground="#c0a0c0" >
					<column name="Имя пользователя" type="string" />
					<column name="Имя пользователя" type="string" />
					<column name="Дата начала" type="int" />
					<column name="Дата окончания" type="int" />
					<column name="Протокол" type="string" />
				</table>
			</frame>			
		</getdata>
	</chart>

  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3_port.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="14" />
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" />
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
	  <insertblock blockformat="bf1"/>
      <inserttext text="Скорость по портам" textformat="tf1"/>
      <insertblock blockformat="defbf"/>
    </frame>    
    <insertblock />
	<insertblock />
	<insertblock />

	<chart library="pychartdir" name="chart1" type="nfs_port_speed">
		<getdata>
				<frame name="fr2" datasource="args" type="current" format="currentnew" fname="tff1">
					<insertblock />
					<insertblock />
					<inserttext text="Дата начала: " textformat="tf2" />
					<insertdatanontext index = '0' />
					<insertblock />
					<inserttext text="Дата окончания: "/>
					<insertdatanontext index = '1' />
					<insertblock />
					<insertblock />
			</frame>
		</getdata>		
	</chart>

  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3_users.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
	<textformat name="whitetf10" setFontWeight="72" setFontPointSize="10" setForeground="#FFFFFF" />
	<textformat name="stf1" setFontWeight="72" setFontPointSize="12" setForeground="#3d3d3d" />
	<textformat name="stf2" setFontWeight="72" setFontPointSize="11" setForeground="#5e93b6" />
	<textformat name="stf3" setFontWeight="36" setFontPointSize="11" setForeground="#000000" />
	<blockformat name="centerbf" setAlignment="22" />
	<frame name="topframe" format="currentedit" setWidth="840" fname="topff" padding="0">
		<image path="images/reports/header.png" />
		<frame name="uprblockfr" format="new" fname="ubff" setHeight="50" setWidth="840" padding="4" setBackground="#323232">
			<insertblock blockformat="centerbf" />
			<inserttext text="Отчёт по классам траффика с выбором пользователя" textformat="whitetf10" />
			<insertblock />
		</frame>
		<frame name="cframe" type="existing" format="new" setWidth="840" fname="cff">
			<insertblock blockformat="centerbf" />

	<chart library="pychartdir" name="chart1" type="nfs_total_users_traf">
		<getdata>
			<selstring name="get_tarifs" dataid="ch1data2"/>
		</getdata>
		<getdata>
			<selstring name="get_accounts" dataid="ch1data1"/>		
		</getdata>
		<getdata>
			<selstring name="get_nas" dataid="ch1datanas"/>
		</getdata>		
	</chart>
	<insertblock blockformat="centerbf" />
			<stable name="schtbl1" rownum="1" colnum="1" ftype="new" fname="schtf" setAlignment="22" setCellPadding="0" setBorderStyle="0">
				<scell row="0" col="0">
					<table name="tbl2" columns="5" type="normal" datasource="ch1data1" arheader="Выбранные пользователи: "  fname="tf2" ftype="new" setCellPadding="2" setCellSpacing="2"  setBackground="#ececec" setAlignment="22">
					<column name="ID" type="int" />
					<column name="Username" type="string" />
					<column name="VPN IP" type="string" />
					<column name="IPN IP" type="string" />
					<column name="Тарифы" type="table" datasource="ch1data2" imerge="0" ibase="1" tftype="new" tfname="zomg" setBorder="1" colConstrType="percentage" colConstraints="70, 30" setAlignment="22"/>
				</table>
				</scell>
			</stable>
			<insertblock blockformat="centerbf" />
			<stable name="schtbl2" rownum="1" colnum="1" ftype="new" fname="schtf" setAlignment="22" setCellPadding="0" setBorderStyle="0">
				<scell row="0" col="0">
					<table name="tbl3" columns="2" type="normal" datasource="ch1datanas" ftype="new" setCellPadding="2" setBackground="#ececec" fname="tf2" arheader="Выбранные серверы доступа: ">
					<column name="Имя" type="string" />
					<column name="Тип" type="string" />
				</table>
				</scell>
			</stable>
	</frame>
		<frame name="chtbl2fr" datasource="args" type="current" format="currentnew" setWidth="840" fname="chtbl2ff">
			<insertblock />
			<insertblock blockformat="centerbf" />
			<inserttext text="ПЕРИОД: " textformat="stf1" />
			<inserttext text="с " textformat="stf3" />
			<insertdatanontext index="0" textformat="stf2" />
			<inserttext text=" по " textformat="stf3" />
			<insertdatanontext index="1" textformat="stf2" />
			<insertblock />
			<insertblock />
		</frame>
  </frame>
</report>
