=== brat002/ExpertBilling/mdi/reports/xml/report_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="report">
    <xs:complexType>
      <xs:sequence>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="textformat">
            <xs:complexType>
              <xs:complexContent mixed="false">
                <xs:extension base="textformat" />
              </xs:complexContent>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="blockformat" type="blockformat" />
        </xs:sequence>
        <xs:element name="frame">
          <xs:complexType>
            <xs:complexContent mixed="false">
              <xs:extension base="frame">
                <xs:choice />
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="frame">
    <xs:all minOccurs="0" maxOccurs="1">
      <xs:element minOccurs="0" maxOccurs="1" name="frame" type="frame" />
      <xs:element minOccurs="0" name="inserttext" type="insertText" />
      <xs:element minOccurs="0" name="insertblock" type="insertBlock" />
      <xs:element minOccurs="0" name="frameformat" type="frameformat" />
      <xs:element minOccurs="0" name="chart" type="chart" />
      <xs:element minOccurs="0" name="table">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension base="table" />
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="insertnontext" type="insertNonText" />
      <xs:element minOccurs="0" name="insertdatatext" type="insertDataText" />
      <xs:element minOccurs="0" name="insertdatanontext" type="insertDataNonText" />
      <xs:element minOccurs="0" name="data">
        <xs:complexType>
          <xs:attribute name="dataid" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="format" type="xs:string" use="optional" />
    <xs:attribute name="fname" type="xs:string" use="optional" />
    <xs:attribute name="formattype" use="optional" />
    <xs:attribute name="setBorder" use="optional" />
    <xs:attribute name="setHeight" use="optional" />
    <xs:attribute name="setWidth" use="optional" />
    <xs:attribute name="setPosition" use="optional" />
    <xs:attribute name="setMargin" use="optional" />
    <xs:attribute name="setPadding" use="optional" />
    <xs:attribute name="setBorderStyle" use="optional" />
    <xs:attribute name="datasource" use="optional" />
    <xs:attribute name="setBackground" use="optional" />
    <xs:attribute name="setTextColor" />
  </xs:complexType>
  <xs:complexType name="insertText">
    <xs:attribute name="text" type="xs:string" />
    <xs:attribute name="textformat" use="optional" />
  </xs:complexType>
  <xs:complexType name="insertBlock">
    <xs:attribute name="number" use="optional" />
    <xs:attribute name="blockformat" use="optional" />
  </xs:complexType>
  <xs:complexType name="chart">
    <xs:all minOccurs="0" maxOccurs="1">
      <xs:element minOccurs="0" name="charttable" type="table" />
      <xs:element minOccurs="0" maxOccurs="1" name="frameformat">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension base="frameformat" />
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="getdata">
        <xs:complexType>
          <xs:all maxOccurs="1">
            <xs:element minOccurs="0" name="selstring">
              <xs:complexType>
                <xs:attribute name="name" use="required" />
                <xs:attribute name="type" use="required" />
                <xs:attribute name="dataid" />
              </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="frame" type="frame" />
            <xs:element minOccurs="0" name="table" type="table" />
          </xs:all>
          <xs:attribute name="name" use="optional" />
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="options" />
      <xs:element minOccurs="0" name="frame" type="frame" />
    </xs:all>
    <xs:attribute name="library" use="optional" />
    <xs:attribute name="name" />
    <xs:attribute name="type" />
    <xs:attribute name="outtype" use="optional" />
  </xs:complexType>
  <xs:complexType name="frameformat">
    <xs:attribute name="setBorder" use="optional" />
    <xs:attribute name="setHeight" use="optional" />
    <xs:attribute name="setWidth" use="optional" />
    <xs:attribute name="setPosition" use="optional" />
    <xs:attribute name="setMargin" use="optional" />
    <xs:attribute name="setBorderStyle" use="optional" />
    <xs:attribute name="setPadding" use="optional" />
    <xs:attribute name="format" use="optional" />
    <xs:attribute name="fname" use="optional" />
    <xs:attribute name="name" use="optional" />
    <xs:attribute name="setBorder" use="optional" />
  </xs:complexType>
  <xs:complexType name="textformat">
    <xs:attribute name="name" />
    <xs:attribute name="setFontWeight" use="optional" />
    <xs:attribute name="setFontItalic" use="optional" />
    <xs:attribute name="setFontUnderline" use="optional" />
    <xs:attribute name="setFontFamily" use="optional" />
    <xs:attribute name="setFontPointSize" use="optional" />
    <xs:attribute name="setForeground" use="optional" />
    <xs:attribute name="setBackground" use="optional" />
  </xs:complexType>
  <xs:complexType name="table">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="column">
        <xs:complexType>
          <xs:attribute name="name" use="optional" />
          <xs:attribute name="type" />
          <xs:attribute name="format" use="optional" />
          <xs:attribute name="nameformat" use="optional" />
          <xs:attribute name="datasource" use="optional" />
          <xs:attribute name="imerge" use="optional" />
          <xs:attribute name="ibase" use="optional" />
          <xs:attribute name="tftype" use="optional" />
          <xs:attribute name="tformat" use="optional" />
          <xs:attribute name="tfname" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" />
    <xs:attribute name="columns" />
    <xs:attribute name="fname" use="required" />
    <xs:attribute name="ftype" />
    <xs:attribute name="setAlignment" use="optional" />
    <xs:attribute name="setCellPadding" use="optional" />
    <xs:attribute name="setCellSpacing" use="optional" />
    <xs:attribute name="data" use="optional" />
    <xs:attribute name="dictdata" use="optional" />
    <xs:attribute name="datasource" use="optional" />
    <xs:attribute name="type" use="required" />
    <xs:attribute name="arheader" use="optional" />
    <xs:attribute name="colnametf" />
    <xs:attribute name="arheadtf" />
    <xs:attribute name="celltf" />
    <xs:attribute name="arheadbf" use="optional" />
    <xs:attribute name="colConstrType" use="optional" />
    <xs:attribute name="colConstraints" use="optional" />
  </xs:complexType>
  <xs:complexType name="insertNonText">
    <xs:complexContent mixed="false">
      <xs:extension base="insertText">
        <xs:attribute name="format" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="insertDataText">
    <xs:complexContent mixed="false">
      <xs:extension base="insertText">
        <xs:attribute name="dict" use="optional" />
        <xs:attribute name="key" use="optional" />
        <xs:attribute name="index" use="optional" />
        <xs:attribute name="subindex" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="insertDataNonText">
    <xs:complexContent mixed="false">
      <xs:extension base="insertDataText">
        <xs:attribute name="format" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="moveCursor">
    <xs:attribute name="position" />
    <xs:attribute name="type" />
    <xs:attribute name="framename" use="optional" />
  </xs:complexType>
  <xs:complexType name="blockformat">
    <xs:attribute name="setAlignment" />
    <xs:attribute name="name" />
  </xs:complexType>
</xs:schema>

=== brat002/ExpertBilling/mdi/reports/xml/report3_nas.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="14" />
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" />
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
	  <insertblock blockformat="bf1"/>
      <inserttext text="Отчёт по классам траффика с выбором пользователя" textformat="tf1"/>
      <insertblock blockformat="defbf"/>
    </frame>    
    <insertblock />
	<insertblock />
	<insertblock />

	<chart library="pychartdir" name="chart1" type="nfs_user_traf">
		<getdata>
			<selstring name="get_tarifs" dataid="ch1data2"/>
				<frame name="fr2" datasource="args" type="current" format="currentnew" fname="tff1">
					<insertblock />
					<insertblock />
					<inserttext text="Дата начала: " textformat="tf2" />
					<insertdatanontext index = '1' />
					<insertblock />
					<inserttext text="Дата окончания: "/>
					<insertdatanontext index = '2' />
					<insertblock />
					<insertblock />
			</frame>
		</getdata>
		<getdata>
			<selstring name="get_accounts" dataid="ch1data1"/>
			<frame name="ch1fr1" datasource="ch1data1" type="current" format="current">
				<inserttext text="Выбранные пользователи: "/>
				<insertblock/>
				<table name="tbl2" columns="5" type="normal"  fname="tf2" ftype="new" setCellPadding="2"  setBackground="#c0a0c0" >
					<column name="ID" type="int" />
					<column name="username" type="string" />
					<column name="vpn ip" type="string" />
					<column name="upn ip" type="string" />
					<column name="тарифы" type="table" datasource="ch1data2" imerge="0" ibase="1"/>
				</table>
			</frame>			
		</getdata>
		<getdata>
			<selstring name="get_nas" dataid="ch1datanas"/>
			<insertblock/>
			<insertblock/>
			<insertblock/>
			
			<frame name="ch1fr4" datasource="ch1datanas" type="current" format="current">
				<table name="tbl3" columns="2" type="normal" ftype="existing" fname="tf2" arheader="Выбранные серверы доступа: ">
					<column name="Имя" type="string" />
					<column name="Тип" type="string" />
				</table>
			</frame>
		</getdata>		
	</chart>

  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report2.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="77" setFontItalic="true"/>
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
      <inserttext text="string" />
      <insertblock />
    </frame>
    <inserttext text="дапашолты" />
    <insertblock />
	<chart library="pychartdir" name="chart1" type="nfs_total_traf">
		<getdata>
			<selstring name="get_accounts" dataid="ch1data1"/>
			<frame name="ch1fr1" datasource="ch1data1" type="current" format="current">
				<inserttext text="ID"/>
				<insertblock/>
				<insertdatanontext index = '0' subindex="0"/>
				<insertblock/>
				<inserttext text="uname"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="1"/>
				<insertblock/>
				<inserttext text="VPN IP"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="2"/>
				<insertblock/>
				<inserttext text="UPN IP"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="3"/>
				<insertblock/>
				<inserttext text="                  "/>
				<table name="tbl2" columns="4" type="normal"  fname="tf2" ftype="new" setAlignment="22" setCellPadding="2" celltf="tf1">
					<column name="ID" type="int" />
					<column name="uname" type="string" />
					<column name="vpn ip" type="string" />
					<column name="upn ip" type="string" />
				</table>
			</frame>			
		</getdata>
		<getdata>
			<selstring name="get_tarifs" dataid="ch1data2"/>
			<frame name="ch1fr2" datasource="ch1data2"  format="new" fname="nnn" setBorder="12" setBorderStyle="2" setPosition="0" setWidth="69%" >
				<inserttext text="ZOMG TABLE" textformat="tf1"/>
				<insertblock/>
				<table name="tbl1" columns="2" type="array" arheader="              Table for account ID: %d" setAlignment="22" fname="tf1" ftype="new" colnametf="tf1" arheadtf="tf1">
					<column name="Tariff" type="string" />
					<column name="Date" type="string" />
				</table>
			</frame>
		</getdata>
	</chart>
	<inserttext text="ахшобцибя"/>
	<insertblock/>
  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3_pie.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="18" setFontItalic="true" setForeground="#00ff00"/>
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" />
  <textformat name="tf3" setFontWeight="72" setFontPointSize="10" setForeground="#FFFFFF" />
  <textformat name="stf1" setFontWeight="72" setFontPointSize="12" setForeground="#3d3d3d" />
  <textformat name="stf2" setFontWeight="72" setFontPointSize="11" setForeground="#5e93b6" />
  <textformat name="stf3" setFontWeight="36" setFontPointSize="11" setForeground="#000000" />
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe"  type="current" format="currentedit" setWidth="1000"  fname="tff" padding="16">
	<image path="images/reports/header.png"/>
	
	<frame name="blfr"  type="insert" format="new" fname="rff" setHeight="50" setWidth="1000" padding="4"  setBackground="#323232">
		<insertblock blockformat="bf1"/>
		<inserttext text="Траффик пользователей" textformat="tf3" />
		<insertblock />
	</frame>

	<frame name="cframe"  type="existing" format="new" setWidth="1000" fname="tff7">
	<stable name="stbl2" rownum="1" colnum="2" ftype="new" fname="stf1" setAlignment="22" setCellPadding="0" setBorderStyle="0">
		<scell row="0" col="0">
			<chart library="pychartdir" name="chart1" type="userstrafpie">	
				<getdata/>
			</chart>
		</scell>
		<scell row="0" col="1">
			<table name="tbl2" columns="2" datasource="chart1_return"  type="normal"  fname="tf2" ftype="new" setCellPadding="2"  setBackground="#ececec" >
				<column name="Имя пользователя" type="string" />
				<column name="Траффик" type="int" />
			</table>
		</scell>
	</stable>
		
				
	</frame>
	<frame name="fr2" datasource="args" type="current" format="currentnew" setWidth="1000" fname="tff1">
		<insertblock />
		<insertblock blockformat="bf1"/>
		<inserttext text="ПЕРИОД: " textformat="stf1" />
		<inserttext text="с " textformat="stf3" />
		<insertdatanontext index = '0' textformat="stf2" />
		<inserttext text=" по " textformat="stf3" />
		<insertdatanontext index = '1' textformat="stf2"/>
		<insertblock />
		<insertblock />
	</frame>
  </frame>
</report>

=== brat002/ExpertBilling/mdi/reports/xml/report3.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="report_schema.xsd">
  <textformat name="tf1" setFontWeight="96" setFontPointSize="18" setFontItalic="true" setForeground="#00ff00"/>
  <textformat name="tf2" setFontWeight="72" setFontPointSize="12" setFontItalic="true" setForeground="#00ff00"/>
  <blockformat name="bf1" setAlignment="22" />
  <frame name="topframe" type="current" format="currentedit" fname="tff" padding="16">
    <frame name="referenceframe" type="insert" format="new" fname="rff" formattype="textframe" padding="16">
	  <insertblock blockformat="bf1"/>
      <inserttext text="Отчёт по классам траффика с выбором пользователя" textformat="tf1"/>
      <insertblock blockformat="defbf"/>
    </frame>    
    <insertblock />
	<insertblock />
	<insertblock />
	<frame name="fr2" datasource="args" type="current" format="currentnew" fname="tff1">
		<inserttext text="Input data: " textformat="tf2" />
		<insertblock />
		<insertblock />
		<inserttext text="User ID: "/>
		<insertdatanontext index = '0' />
		<insertblock />
		<inserttext text="DOS: "/>
		<insertdatanontext index = '1' />
		<insertblock />
		<inserttext text="DOE: "/>
		<insertdatanontext index = '2' />
		<insertblock />
		<insertblock />
	</frame>
	<chart library="pychartdir" name="chart1" type="nfs_user_traf">
		<getdata>
			<selstring name="get_accounts" dataid="ch1data1"/>
			<frame name="fr3" datasource="chart1_return" type="current" format="current">
				<insertblock />
				<inserttext text="Aggregated by: "/>
				<insertdatanontext key="sec" />
				<inserttext text="    seconds"/>
				<insertblock />
			</frame>
			<frame name="ch1fr1" datasource="ch1data1" type="current" format="current">
				<inserttext text="ID"/>
				<insertblock/>
				<insertdatanontext index = '0' subindex="0"/>
				<insertblock/>
				<inserttext text="uname"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="1"/>
				<insertblock />
				<inserttext text="VPN IP"/>
				<insertblock />
				<insertdatatext index = '0' subindex="2"/>
				<insertblock/>
				<inserttext text="UPN IP"/>
				<insertblock/>
				<insertdatatext index = '0' subindex="3"/>
				<insertblock/>
				<inserttext text="                  "/>
				<table name="tbl2" columns="4" type="normal"  fname="tf2" ftype="new" setCellPadding="2"  setBackground="#c0a0c0" >
					<column name="ID" type="int" />
					<column name="uname" type="string" />
					<column name="vpn ip" type="string" />
					<column name="upn ip" type="string" />
				</table>
			</frame>			
		</getdata>
		<getdata>
			<selstring name="get_tarifs" dataid="ch1data2"/>
			<frame name="ch1fr2" datasource="ch1data2"  format="new" fname="nnn"  setBorderStyle="2" setPosition="0" >
				<inserttext text="Таблицы" textformat="tf2"/>
				<insertblock/>
				<table name="tbl1" columns="2" type="array" ftype="new" arheader="              Table for account ID: %s" setAlignment="22" fname="tf1"  arheadtf="tf2" arheadbf="bf1">
					<column name="Tariff" type="string" />
					<column name="Date" type="string" />
				</table>
			</frame>
		</getdata>
	</chart>

  </frame>
</report>
